/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin/unauthorized'
import { Route as AdminReportingRouteImport } from './routes/admin/reporting'
import { Route as AdminProfilRouteImport } from './routes/admin/profil'
import { Route as AdminNominationsRouteImport } from './routes/admin/nominations'
import { Route as AdminCongesRouteImport } from './routes/admin/conges'
import { Route as AdminCalendrierRouteImport } from './routes/admin/calendrier'
import { Route as AdminAbsencesRouteImport } from './routes/admin/absences'
import { Route as AdminParametrageIndexRouteImport } from './routes/admin/parametrage/index'
import { Route as AdminLotsIndexRouteImport } from './routes/admin/lots/index'
import { Route as AdminEmployesIndexRouteImport } from './routes/admin/employes/index'
import { Route as AdminParametrageUtilisateursRouteImport } from './routes/admin/parametrage/utilisateurs'
import { Route as AdminParametrageRubriquesRouteImport } from './routes/admin/parametrage/rubriques'
import { Route as AdminParametrageFonctionsRouteImport } from './routes/admin/parametrage/fonctions'
import { Route as AdminParametrageExclusionsRouteImport } from './routes/admin/parametrage/exclusions'
import { Route as AdminParametrageDivisionsRouteImport } from './routes/admin/parametrage/divisions'
import { Route as AdminParametrageCategoriesRouteImport } from './routes/admin/parametrage/categories'
import { Route as AdminParametrageAttributionsIndividuellesRouteImport } from './routes/admin/parametrage/attributions-individuelles'
import { Route as AdminParametrageAttributionsRouteImport } from './routes/admin/parametrage/attributions'
import { Route as AdminLotsLotIdRouteImport } from './routes/admin/lots/$lotId'
import { Route as AdminEmployesEmployeeIdRouteImport } from './routes/admin/employes/$employeeId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportingRoute = AdminReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilRoute = AdminProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNominationsRoute = AdminNominationsRouteImport.update({
  id: '/nominations',
  path: '/nominations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCongesRoute = AdminCongesRouteImport.update({
  id: '/conges',
  path: '/conges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendrierRoute = AdminCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbsencesRoute = AdminAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametrageIndexRoute = AdminParametrageIndexRouteImport.update({
  id: '/parametrage/',
  path: '/parametrage/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotsIndexRoute = AdminLotsIndexRouteImport.update({
  id: '/lots/',
  path: '/lots/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployesIndexRoute = AdminEmployesIndexRouteImport.update({
  id: '/employes/',
  path: '/employes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametrageUtilisateursRoute =
  AdminParametrageUtilisateursRouteImport.update({
    id: '/parametrage/utilisateurs',
    path: '/parametrage/utilisateurs',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageRubriquesRoute =
  AdminParametrageRubriquesRouteImport.update({
    id: '/parametrage/rubriques',
    path: '/parametrage/rubriques',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageFonctionsRoute =
  AdminParametrageFonctionsRouteImport.update({
    id: '/parametrage/fonctions',
    path: '/parametrage/fonctions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageExclusionsRoute =
  AdminParametrageExclusionsRouteImport.update({
    id: '/parametrage/exclusions',
    path: '/parametrage/exclusions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageDivisionsRoute =
  AdminParametrageDivisionsRouteImport.update({
    id: '/parametrage/divisions',
    path: '/parametrage/divisions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageCategoriesRoute =
  AdminParametrageCategoriesRouteImport.update({
    id: '/parametrage/categories',
    path: '/parametrage/categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageAttributionsIndividuellesRoute =
  AdminParametrageAttributionsIndividuellesRouteImport.update({
    id: '/parametrage/attributions-individuelles',
    path: '/parametrage/attributions-individuelles',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminParametrageAttributionsRoute =
  AdminParametrageAttributionsRouteImport.update({
    id: '/parametrage/attributions',
    path: '/parametrage/attributions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLotsLotIdRoute = AdminLotsLotIdRouteImport.update({
  id: '/lots/$lotId',
  path: '/lots/$lotId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployesEmployeeIdRoute = AdminEmployesEmployeeIdRouteImport.update({
  id: '/employes/$employeeId',
  path: '/employes/$employeeId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/absences': typeof AdminAbsencesRoute
  '/admin/calendrier': typeof AdminCalendrierRoute
  '/admin/conges': typeof AdminCongesRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/employes/$employeeId': typeof AdminEmployesEmployeeIdRoute
  '/admin/lots/$lotId': typeof AdminLotsLotIdRoute
  '/admin/parametrage/attributions': typeof AdminParametrageAttributionsRoute
  '/admin/parametrage/attributions-individuelles': typeof AdminParametrageAttributionsIndividuellesRoute
  '/admin/parametrage/categories': typeof AdminParametrageCategoriesRoute
  '/admin/parametrage/divisions': typeof AdminParametrageDivisionsRoute
  '/admin/parametrage/exclusions': typeof AdminParametrageExclusionsRoute
  '/admin/parametrage/fonctions': typeof AdminParametrageFonctionsRoute
  '/admin/parametrage/rubriques': typeof AdminParametrageRubriquesRoute
  '/admin/parametrage/utilisateurs': typeof AdminParametrageUtilisateursRoute
  '/admin/employes/': typeof AdminEmployesIndexRoute
  '/admin/lots/': typeof AdminLotsIndexRoute
  '/admin/parametrage/': typeof AdminParametrageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin/absences': typeof AdminAbsencesRoute
  '/admin/calendrier': typeof AdminCalendrierRoute
  '/admin/conges': typeof AdminCongesRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin': typeof AdminIndexRoute
  '/admin/employes/$employeeId': typeof AdminEmployesEmployeeIdRoute
  '/admin/lots/$lotId': typeof AdminLotsLotIdRoute
  '/admin/parametrage/attributions': typeof AdminParametrageAttributionsRoute
  '/admin/parametrage/attributions-individuelles': typeof AdminParametrageAttributionsIndividuellesRoute
  '/admin/parametrage/categories': typeof AdminParametrageCategoriesRoute
  '/admin/parametrage/divisions': typeof AdminParametrageDivisionsRoute
  '/admin/parametrage/exclusions': typeof AdminParametrageExclusionsRoute
  '/admin/parametrage/fonctions': typeof AdminParametrageFonctionsRoute
  '/admin/parametrage/rubriques': typeof AdminParametrageRubriquesRoute
  '/admin/parametrage/utilisateurs': typeof AdminParametrageUtilisateursRoute
  '/admin/employes': typeof AdminEmployesIndexRoute
  '/admin/lots': typeof AdminLotsIndexRoute
  '/admin/parametrage': typeof AdminParametrageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/absences': typeof AdminAbsencesRoute
  '/admin/calendrier': typeof AdminCalendrierRoute
  '/admin/conges': typeof AdminCongesRoute
  '/admin/nominations': typeof AdminNominationsRoute
  '/admin/profil': typeof AdminProfilRoute
  '/admin/reporting': typeof AdminReportingRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/employes/$employeeId': typeof AdminEmployesEmployeeIdRoute
  '/admin/lots/$lotId': typeof AdminLotsLotIdRoute
  '/admin/parametrage/attributions': typeof AdminParametrageAttributionsRoute
  '/admin/parametrage/attributions-individuelles': typeof AdminParametrageAttributionsIndividuellesRoute
  '/admin/parametrage/categories': typeof AdminParametrageCategoriesRoute
  '/admin/parametrage/divisions': typeof AdminParametrageDivisionsRoute
  '/admin/parametrage/exclusions': typeof AdminParametrageExclusionsRoute
  '/admin/parametrage/fonctions': typeof AdminParametrageFonctionsRoute
  '/admin/parametrage/rubriques': typeof AdminParametrageRubriquesRoute
  '/admin/parametrage/utilisateurs': typeof AdminParametrageUtilisateursRoute
  '/admin/employes/': typeof AdminEmployesIndexRoute
  '/admin/lots/': typeof AdminLotsIndexRoute
  '/admin/parametrage/': typeof AdminParametrageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/register'
    | '/admin/absences'
    | '/admin/calendrier'
    | '/admin/conges'
    | '/admin/nominations'
    | '/admin/profil'
    | '/admin/reporting'
    | '/admin/unauthorized'
    | '/admin/'
    | '/admin/employes/$employeeId'
    | '/admin/lots/$lotId'
    | '/admin/parametrage/attributions'
    | '/admin/parametrage/attributions-individuelles'
    | '/admin/parametrage/categories'
    | '/admin/parametrage/divisions'
    | '/admin/parametrage/exclusions'
    | '/admin/parametrage/fonctions'
    | '/admin/parametrage/rubriques'
    | '/admin/parametrage/utilisateurs'
    | '/admin/employes/'
    | '/admin/lots/'
    | '/admin/parametrage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin/absences'
    | '/admin/calendrier'
    | '/admin/conges'
    | '/admin/nominations'
    | '/admin/profil'
    | '/admin/reporting'
    | '/admin/unauthorized'
    | '/admin'
    | '/admin/employes/$employeeId'
    | '/admin/lots/$lotId'
    | '/admin/parametrage/attributions'
    | '/admin/parametrage/attributions-individuelles'
    | '/admin/parametrage/categories'
    | '/admin/parametrage/divisions'
    | '/admin/parametrage/exclusions'
    | '/admin/parametrage/fonctions'
    | '/admin/parametrage/rubriques'
    | '/admin/parametrage/utilisateurs'
    | '/admin/employes'
    | '/admin/lots'
    | '/admin/parametrage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/register'
    | '/admin/absences'
    | '/admin/calendrier'
    | '/admin/conges'
    | '/admin/nominations'
    | '/admin/profil'
    | '/admin/reporting'
    | '/admin/unauthorized'
    | '/admin/'
    | '/admin/employes/$employeeId'
    | '/admin/lots/$lotId'
    | '/admin/parametrage/attributions'
    | '/admin/parametrage/attributions-individuelles'
    | '/admin/parametrage/categories'
    | '/admin/parametrage/divisions'
    | '/admin/parametrage/exclusions'
    | '/admin/parametrage/fonctions'
    | '/admin/parametrage/rubriques'
    | '/admin/parametrage/utilisateurs'
    | '/admin/employes/'
    | '/admin/lots/'
    | '/admin/parametrage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reporting': {
      id: '/admin/reporting'
      path: '/reporting'
      fullPath: '/admin/reporting'
      preLoaderRoute: typeof AdminReportingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profil': {
      id: '/admin/profil'
      path: '/profil'
      fullPath: '/admin/profil'
      preLoaderRoute: typeof AdminProfilRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nominations': {
      id: '/admin/nominations'
      path: '/nominations'
      fullPath: '/admin/nominations'
      preLoaderRoute: typeof AdminNominationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conges': {
      id: '/admin/conges'
      path: '/conges'
      fullPath: '/admin/conges'
      preLoaderRoute: typeof AdminCongesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendrier': {
      id: '/admin/calendrier'
      path: '/calendrier'
      fullPath: '/admin/calendrier'
      preLoaderRoute: typeof AdminCalendrierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/absences': {
      id: '/admin/absences'
      path: '/absences'
      fullPath: '/admin/absences'
      preLoaderRoute: typeof AdminAbsencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/': {
      id: '/admin/parametrage/'
      path: '/parametrage'
      fullPath: '/admin/parametrage/'
      preLoaderRoute: typeof AdminParametrageIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lots/': {
      id: '/admin/lots/'
      path: '/lots'
      fullPath: '/admin/lots/'
      preLoaderRoute: typeof AdminLotsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employes/': {
      id: '/admin/employes/'
      path: '/employes'
      fullPath: '/admin/employes/'
      preLoaderRoute: typeof AdminEmployesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/utilisateurs': {
      id: '/admin/parametrage/utilisateurs'
      path: '/parametrage/utilisateurs'
      fullPath: '/admin/parametrage/utilisateurs'
      preLoaderRoute: typeof AdminParametrageUtilisateursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/rubriques': {
      id: '/admin/parametrage/rubriques'
      path: '/parametrage/rubriques'
      fullPath: '/admin/parametrage/rubriques'
      preLoaderRoute: typeof AdminParametrageRubriquesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/fonctions': {
      id: '/admin/parametrage/fonctions'
      path: '/parametrage/fonctions'
      fullPath: '/admin/parametrage/fonctions'
      preLoaderRoute: typeof AdminParametrageFonctionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/exclusions': {
      id: '/admin/parametrage/exclusions'
      path: '/parametrage/exclusions'
      fullPath: '/admin/parametrage/exclusions'
      preLoaderRoute: typeof AdminParametrageExclusionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/divisions': {
      id: '/admin/parametrage/divisions'
      path: '/parametrage/divisions'
      fullPath: '/admin/parametrage/divisions'
      preLoaderRoute: typeof AdminParametrageDivisionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/categories': {
      id: '/admin/parametrage/categories'
      path: '/parametrage/categories'
      fullPath: '/admin/parametrage/categories'
      preLoaderRoute: typeof AdminParametrageCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/attributions-individuelles': {
      id: '/admin/parametrage/attributions-individuelles'
      path: '/parametrage/attributions-individuelles'
      fullPath: '/admin/parametrage/attributions-individuelles'
      preLoaderRoute: typeof AdminParametrageAttributionsIndividuellesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parametrage/attributions': {
      id: '/admin/parametrage/attributions'
      path: '/parametrage/attributions'
      fullPath: '/admin/parametrage/attributions'
      preLoaderRoute: typeof AdminParametrageAttributionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lots/$lotId': {
      id: '/admin/lots/$lotId'
      path: '/lots/$lotId'
      fullPath: '/admin/lots/$lotId'
      preLoaderRoute: typeof AdminLotsLotIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employes/$employeeId': {
      id: '/admin/employes/$employeeId'
      path: '/employes/$employeeId'
      fullPath: '/admin/employes/$employeeId'
      preLoaderRoute: typeof AdminEmployesEmployeeIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAbsencesRoute: typeof AdminAbsencesRoute
  AdminCalendrierRoute: typeof AdminCalendrierRoute
  AdminCongesRoute: typeof AdminCongesRoute
  AdminNominationsRoute: typeof AdminNominationsRoute
  AdminProfilRoute: typeof AdminProfilRoute
  AdminReportingRoute: typeof AdminReportingRoute
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployesEmployeeIdRoute: typeof AdminEmployesEmployeeIdRoute
  AdminLotsLotIdRoute: typeof AdminLotsLotIdRoute
  AdminParametrageAttributionsRoute: typeof AdminParametrageAttributionsRoute
  AdminParametrageAttributionsIndividuellesRoute: typeof AdminParametrageAttributionsIndividuellesRoute
  AdminParametrageCategoriesRoute: typeof AdminParametrageCategoriesRoute
  AdminParametrageDivisionsRoute: typeof AdminParametrageDivisionsRoute
  AdminParametrageExclusionsRoute: typeof AdminParametrageExclusionsRoute
  AdminParametrageFonctionsRoute: typeof AdminParametrageFonctionsRoute
  AdminParametrageRubriquesRoute: typeof AdminParametrageRubriquesRoute
  AdminParametrageUtilisateursRoute: typeof AdminParametrageUtilisateursRoute
  AdminEmployesIndexRoute: typeof AdminEmployesIndexRoute
  AdminLotsIndexRoute: typeof AdminLotsIndexRoute
  AdminParametrageIndexRoute: typeof AdminParametrageIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbsencesRoute: AdminAbsencesRoute,
  AdminCalendrierRoute: AdminCalendrierRoute,
  AdminCongesRoute: AdminCongesRoute,
  AdminNominationsRoute: AdminNominationsRoute,
  AdminProfilRoute: AdminProfilRoute,
  AdminReportingRoute: AdminReportingRoute,
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployesEmployeeIdRoute: AdminEmployesEmployeeIdRoute,
  AdminLotsLotIdRoute: AdminLotsLotIdRoute,
  AdminParametrageAttributionsRoute: AdminParametrageAttributionsRoute,
  AdminParametrageAttributionsIndividuellesRoute:
    AdminParametrageAttributionsIndividuellesRoute,
  AdminParametrageCategoriesRoute: AdminParametrageCategoriesRoute,
  AdminParametrageDivisionsRoute: AdminParametrageDivisionsRoute,
  AdminParametrageExclusionsRoute: AdminParametrageExclusionsRoute,
  AdminParametrageFonctionsRoute: AdminParametrageFonctionsRoute,
  AdminParametrageRubriquesRoute: AdminParametrageRubriquesRoute,
  AdminParametrageUtilisateursRoute: AdminParametrageUtilisateursRoute,
  AdminEmployesIndexRoute: AdminEmployesIndexRoute,
  AdminLotsIndexRoute: AdminLotsIndexRoute,
  AdminParametrageIndexRoute: AdminParametrageIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
